stages:
  - test
  - build

test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests... This will take about 10 seconds."
    - sleep 10
    - echo "Code coverage is tbd. No unit tests in place"

build-job:
  stage: build
  image: node:latest
  script:
    - echo "building app"
  artifacts:
    expire_in: 2 hrs
    paths:
      - dist